---
title: "Model"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
library(knitr)
library(car)
library(zoo)
library(lmtest)
library(MASS)
library(crayon)
library(lmerTest)
library(sjstats)
opts_chunk$set(message = FALSE, warning = FALSE, tidy = TRUE)
```

```{r include=FALSE}
regression.diagnostics <- function(fit) {
  par(mfrow = c(2, 3))
  plot(fit, which = 1:5)
  influencePlot(fit)
  
  cat("异常值/强影响点检验\n")
  print(outlierTest(fit))
  
  cat("\n异方差检验\n")
  print(ncvTest(fit))
  print(bptest(fit))
  print(gqtest(fit))
  
  cat("\n共线性检验\n")
  print(vif(fit))
  
  cat("\n自相关检验\n")
  print(durbinWatsonTest(fit))
}
```

## Sensitivity Analysis

### Different choice of $\Delta t$

$\Delta t = 1$

```{r}
df = read.csv("../Data/Preprocessed/model_1_days_delta.csv")
fit <- lmer(formula = InfectionGrowth ~ Restrictions.on.gatherings_Level_2 + Public.information.campaigns_Level_2 + Testing.policy_Level_2 + Facial.Coverings_Level_2 + Vaccination.policy_Level_2 + (1 | RegionName), data = df)
summary(fit)
r2(fit)
```

$\Delta t = 3$

```{r}
df = read.csv("../Data/Preprocessed/model_3_days_delta.csv")
fit <- lmer(formula = InfectionGrowth ~ Restrictions.on.gatherings_Level_2 + Public.information.campaigns_Level_2 + Testing.policy_Level_2 + Facial.Coverings_Level_2 + Vaccination.policy_Level_2 + (1 | RegionName), data = df)
summary(fit)
r2(fit)
```

$\Delta t = 7$

```{r}
df = read.csv("../Data/Preprocessed/model_7_days_delta.csv")
fit <- lmer(formula = InfectionGrowth ~ Restrictions.on.gatherings_Level_2 + Public.information.campaigns_Level_2 + Testing.policy_Level_2 + Facial.Coverings_Level_2 + Vaccination.policy_Level_2 + (1 | RegionName), data = df)
summary(fit)
r2(fit)
```

$\Delta t = 14$

```{r}
df = read.csv("../Data/Preprocessed/model_14_days_delta.csv")
fit <- lmer(formula = InfectionGrowth ~ Restrictions.on.gatherings_Level_2 + Public.information.campaigns_Level_2 + Testing.policy_Level_2 + Facial.Coverings_Level_2 + Vaccination.policy_Level_2 + (1 | RegionName), data = df)
summary(fit)
r2(fit)
```

$\Delta t = 21$

```{r}
df = read.csv("../Data/Preprocessed/model_21_days_delta.csv")
fit <- lmer(formula = InfectionGrowth ~ Restrictions.on.gatherings_Level_2 + Public.information.campaigns_Level_2 + Testing.policy_Level_2 + Facial.Coverings_Level_2 + Vaccination.policy_Level_2 + (1 | RegionName), data = df)
summary(fit)
r2(fit)
plot(fit)
```

$\Delta t = 30$

```{r}
df = read.csv("../Data/Preprocessed/model_30_days_delta.csv")
fit <- lmer(formula = InfectionGrowth ~ Restrictions.on.gatherings_Level_2 + Public.information.campaigns_Level_2 + Testing.policy_Level_2 + Facial.Coverings_Level_2 + Vaccination.policy_Level_2 + (1 | RegionName), data = df)
summary(fit)
r2(fit)
```

$\Delta t = 45$

```{r}
df = read.csv("../Data/Preprocessed/model_45_days_delta.csv")
fit <- lmer(formula = InfectionGrowth ~ Restrictions.on.gatherings_Level_2 + Public.information.campaigns_Level_2 + Testing.policy_Level_2 + Facial.Coverings_Level_2 + Vaccination.policy_Level_2 + (1 | RegionName), data = df)
summary(fit)
r2(fit)
```

$\Delta t = 60$

```{r}
df = read.csv("../Data/Preprocessed/model_60_days_delta.csv")
fit <- lmer(formula = InfectionGrowth ~ Restrictions.on.gatherings_Level_2 + Public.information.campaigns_Level_2 + Testing.policy_Level_2 + Facial.Coverings_Level_2 + Vaccination.policy_Level_2 + (1 | RegionName), data = df)
summary(fit)
r2(fit)
```

$\Delta t = 90$

```{r}
df = read.csv("../Data/Preprocessed/model_90_days_delta.csv")
fit <- lmer(formula = InfectionGrowth ~ Restrictions.on.gatherings_Level_2 + Public.information.campaigns_Level_2 + Testing.policy_Level_2 + Facial.Coverings_Level_2 + Vaccination.policy_Level_2 + (1 | RegionName), data = df)
summary(fit)
r2(fit)
```



```{r}
df = read.csv("../Data/Preprocessed/model_21_days_delta.csv")
fit <- lm(formula = InfectionGrowth ~ Restrictions.on.gatherings_Level_2 + Public.information.campaigns_Level_2 + Testing.policy_Level_2 + Facial.Coverings_Level_2 + Vaccination.policy_Level_2, data = df)
summary(fit)
regression.diagnostics(fit)
```
